### PR TITLE
fix issues #223 

### PR DESCRIPTION
**Pull request by pinkykitten**
https://github.com/gocolly/colly/issues/223
Use body response to validate it is html instead of use response header Content-type

### CODE REVIEW

**Comment by asciimoo** [comment]
Detecting the content type this way leads to errors too if the content doesn't start with '<!doctype html>`.
E.g. https://www.imdb.com has an extra whitespace before the docstring declaration.

The proper solution would be a validator public member function which could handle non-standard edge cases too. Something like `Collector.IsHTML func(Response) bool`. What do you think?

**Comment by wforfun** [comment]
Collector. IsHTML func (Response) bool``` 
Agree, can you give me some suggestion? 
Can I getting first 200 character of the body, then confirm it contain `doctype html`

**Comment by vosmith** [comment]
I think checking the `doctype` tag is the right approach, but perhaps the body should be passed through `strings.TrimSpace()` first.  I think any characters other than whitespace would break html parsing any ways.

Or perhaps use `regex` but I'm not sure which would be more efficient.

**Comment by asciimoo** [comment]
These are just heuristics, so I'd like to be able to change it, that's why I suggested a public attribute for this function. I can have a textfile which starts with `<!doctype`, this case it would be good to overwrite the default heuristics function (which checks the content-type and/or the first n bytes of the response).

**Comment by asciimoo** [comment]
Closing due to inactivity.

**Pull request closed without merging**
