### PR TITLE
Add SetClient to set custom http client

### PR DESCRIPTION
**Pull request by geertweening**
So we can use http client and cookie jar across collectors and outside collector

### CODE REVIEW

**Comment by estroz** [comment]
@asciimoo any chance of this getting merged soon?

**Comment by asciimoo** [comment]
I'm not sure if this is the right approach. If the goal is to get the client and the cookie jar, then a `GetClient` and `GetCookieJar` getter is enough. What is the benefit of allowing to set a custom http client?

**Comment by estroz** [comment]
@asciimoo custom testing of a scraper built with colly is an example:

```go
func TestSomeFunction(t *testing.T) {
	s := httptest.NewTLSServer(newTestHandler())
    defer s.Close()
    collector := colly.NewCollector()
    collector.SetClient(s.Client())
	...
}
```

Or if you have other custom client settings.

**Comment by estroz** [comment]
@asciimoo what do you think about my comment above? Apologies for bugging you about this, I really like the project and appreciate your contributions to OSS!

**Pull request merged**
