### PR TITLE
put accept header before OnRequest

### LINKED ISSUE #783: Cannot send request with no Accept header
From `colly.go`:
image

I need to send a request with no headers, but colly automatically inserts "Accept: \*/*" **AFTER** the OnRequest call. So I don't know how to affect it.

Example why I need to do this:
```go
func thisworks() {
	client := &http.Client{}
	req, _ := http.NewRequest("GET", "https://api.yep.com/fs/2/search?client=web&gl=US&no_correct=false&q=youtube&safeSearch=off&type=web", nil)
	//req.Header.Set("Accept", "*/*")
	resp, _ := client.Do(req)

	log.Debug().Msgf("WRequest Header: %v", resp.Request.Header)
	log.Debug().Msgf("WResponse Header: %v", resp.Header)
	body, _ := ioutil.ReadAll(resp.Body)
	log.Debug().Msgf("WResponse Body: %v", string(body))
}

func thisdoesnt() {
	client := &http.Client{}
	req, _ := http.NewRequest("GET", "https://api.yep.com/fs/2/search?client=web&gl=US&no_correct=false&q=youtube&safeSearch=off&type=web", nil)
	req.Header.Set("Accept", "*/*")
	resp, _ := client.Do(req)

	log.Debug().Msgf("Request Header: %v", resp.Request.Header)
	log.Debug().Msgf("Response Header: %v", resp.Header)
	body, _ := ioutil.ReadAll(resp.Body)
	log.Debug().Msgf("Response Body: %v", string(body))
}
```

The two functions give different responses, the only difference being the `req.Header.Set("Accept", "*/*")` line. I need the response that I get when the `Accept` isn't passed.

The good response: `["Ok",{"results":[{"url":"https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664","title":"YouTube: Watch, Liste....`
The bad response: `["Ok",{"results":[{"url":"https://www.commonsensemedia.org/website-reviews/youtube","title":"YouTube Website Review | Co...`

### PR DESCRIPTION
**Pull request by hiddenMedic**
Closes #783 .

### CODE REVIEW

**Review by aleksasiriski — APPROVED** [review]

**Review by WGH- — CHANGES_REQUESTED** [review]
Do you mind writing a unit test for this?

**Comment by hiddenMedic** [comment]
Is that satisfactory? I'm not quite sure what else I could test

**Comment by WGH-** [comment]
> Is that satisfactory? I'm not quite sure what else I could test

Well, the test should ensure that no `Accept` header actually hits the server

**Comment by hiddenMedic** [comment]
Like this?

**Comment by WGH-** [comment]
Right now you only verify what _you think you send_, not what the server sees. Check the existing `TestHeaders` test, it's a good example.

**Comment by hiddenMedic** [comment]
Now? :)

**Review by WGH- — APPROVED** [review]
Great, thanks!

**Pull request merged**
