### PR TITLE
Revisit detection improvement

### PR DESCRIPTION
**Pull request by asalih**
Same request check implemented only GET requests in #77b8884. But  same post bodies also need to be checked and prevent duplicate post requests. Otherwise there is no way to prevent POST requests.

### CODE REVIEW

**Comment by asciimoo** [comment]
Good improvement, thanks. Could you add tests?

**Comment by asalih** [comment]
You are welcome. I've added post revisit check test func. Also, IsVisited func checks request url only. how about implementing a new func like accepting request url and post body, wdyt?

**Comment by asciimoo** [comment]
> how about implementing a new func like accepting request url and post body, wdyt?

Good idea, but it would be good to avoid api break. Perhaps it could be an optional second argument.

**Comment by asalih** [comment]
> > how about implementing a new func like accepting request url and post body, wdyt?
> 
> Good idea, but it would be good to avoid api break. Perhaps it could be an optional second argument.

I've added HasPosted func. No API break, imo. Also calling Seek func were needed for the reader after my pull request and I've fixed it. Tests running successfully.

**Pull request merged**
