### PR TITLE
Add map un-marshaling 

### PR DESCRIPTION
**Pull request by RC1140**
Per the request I had previously where I needed to have a generic struct and then use a map to unmarshal the required attributes.

Issue in question : https://github.com/gocolly/colly/issues/273

### CODE REVIEW

**Comment by asciimoo** [comment]
Please fix travis issues: https://travis-ci.org/gocolly/colly/jobs/489880691

**Comment by RC1140** [comment]
Fixed issues with travis , btw there is an update to github.com/antchfx/htmlquery which breaks colly if its updated. Should I submit a fix for that as well in a separate pull request ?

**Comment by asciimoo** [comment]
> Fixed issues with travis

Awesome, thanks.

> btw there is an update to github.com/antchfx/htmlquery which breaks colly

Again? I fixed one roughly a week ago..

> Should I submit a fix for that as well in a separate pull request ?

Thanks for fixing it. Feel free to push those fixes to this branch too.

**Comment by RC1140** [comment]
Hi , i had an issue with that lib this weekend again ,so i assume its the same issue , will cross check what you committed first

**Comment by asciimoo** [comment]
Great, thanks again.

**Pull request merged**
