### PR TITLE
Implement OnScraped callback

### PR DESCRIPTION
**Pull request by llonchj**
#61

### CODE REVIEW

**Comment by asciimoo** [comment]
What is the purpose of `OnScraped` callback? Seems like it is identical to `OnResponse` callback.

**Comment by llonchj** [comment]
Because I collect information in multiple `OnHTML` callbacks and store data in Ctx, the plan is to use `OnScraped` to perform a final processing of Ctx (aka Scraped item pipeline)

**Comment by asciimoo** [comment]
Ah, I see, so the difference between `OnScraped` and `OnResponse` is that `OnScraped` is called after the `OnHTML` callbacks. Could you please describe it in the docstring of `OnScraped`?

**Comment by llonchj** [comment]
@asciimoo done!

**Comment by llonchj** [comment]
most welcome @asciimoo. Thanks for colly, it's an amazing tool.

**Comment by ash-kamrip** [comment]
There should be separate example for this , explainging the usage of multiple `OnHTML` callbacks and then using the  `OnScraped`

**Pull request merged**
