### PR TITLE
Proxy accessing array in a not thread safe way

### PR DESCRIPTION
**Pull request by i25959341**

### CODE REVIEW

**Comment by i25959341** [comment]
#482

**Comment by WGH-** [comment]
`AddUint32` returns the previous value of the variable. Can't this be safely rewritten as

```go
index := atomic.AddUint32(&r.index, 1) - 1
u := r.proxyURL[index%uint32(len(r.proxyURLs))]
```
instead?

**Comment by i25959341** [comment]
that is better

**Comment by WGH-** [comment]
Oops, correcting myself:

> AddUint32 returns the previous value of the variable.

It actually returns the new value. The code was (and still is) correct, `-1` is indeed necessary so it starts from the first element, it's just my comment was wrong and misleading.

**Comment by i25959341** [comment]
Ya, I sort of got that when I was correcting it, but ya around 5-6 lines better than before

**Pull request merged**
