### PR TITLE
Add OnJSON callback function

### PR DESCRIPTION
**Pull request by 490694561**
When I was crawling the Github API, I found that I needed to repackage the parsing of dynamic json for OnResponse, so I wanted to submit an OnJSON function

Using Example :

```golang
c.OnJSON(func(jsonT []map[string]interface{}) {
	for _, row := range jsonT {
		log.Println(row["login"])
	}
})
```

> I am new to Golang, if the code is not good, please forgive me, tell me, I will modify it

### CODE REVIEW

**Comment by 490694561** [comment]
Somebody else?

**Comment by asciimoo** [comment]
What are the benefits of this callback?

**Comment by 490694561** [comment]
I just think that it will be more convenient for me to crawl the API. If nothing else, I will close the problem myself.

**Comment by 490694561** [comment]
Maybe next time I will learn to issue first, maybe not next time

**Pull request closed without merging**
