### PR TITLE
context.Context Support

### PR DESCRIPTION
**Pull request by Zaba505**
Add Go modules support for Go 1.11, as well as, implemented beta context based API from issue #240

### CODE REVIEW

**Comment by Zaba505** [comment]
Hi @vosmith 

I just created a separate pull request #245 to handle the Go module support. I'll leave this one still open for once #245 is merged in, this request can be merged in, as well.

**Comment by vintik100** [comment]
Take a look my solution... I think is better...
https://github.com/vintik100/colly/commit/3b519735f67ae8c383c97d5421851c3f8d768503

**Comment by vintik100** [comment]
@Zaba505 
Im commited the last version with some fixes... https://github.com/vintik100/colly/commit/bc1b9d30788bab4dfd45b77a3f4e09c2b2060b42 . LimitRule rewrited and now allowing custom Rules implementation... ( For control post requests or create grouping rules, request type rules or  somethink else... )

From the start it not was long-term backwards compatibility, because we "dropping" default context and must be used like new branch or version. Dont like redundant code... This is not ready for open PR , may be one day i will finish it for PR... 

P.S. Sorry for my bad english... 
Regards...

**Comment by Zaba505** [comment]
@vintik100 I closed this PR and opened a new one, #255, based upon our discussion and respective implementations.

**Pull request closed without merging**
