### PR TITLE
feat: support Stop() in queue

### PR DESCRIPTION
**Pull request by PalanQu**
Add feature #528 . @asciimoo

### CODE REVIEW

**Comment by asciimoo** [comment]
It would be nice to have an option to resume after calling `Stop()`.

**Comment by PalanQu** [comment]
> It would be nice to have an option to resume after calling `Stop()`.

Is there any idea about how to resume after calling Stop()?

**Comment by asciimoo** [comment]
@PalanQu what about adding a `Resume()` function which sets `running = true` and calls `Run()`?

**Comment by PalanQu** [comment]
> @PalanQu what about adding a `Resume()` function which sets `running = true` and calls `Run()`? Or, we can modify `Run()` to be able to call it again by setting `running = true` in it.

@asciimoo Thx, I will try.

**Comment by PalanQu** [comment]
@asciimoo Hi, I modified the Run() function, please help me to review this PR, thx.

**Review by asciimoo — APPROVED** [review]
Great, thanks!

**Pull request merged**
